"""Shared compose-override writer for the URL ML canary.

The operator shell may carry stale SAFE_ZONE_* OS environment variables which
would win over ``.env`` during Compose interpolation. To make scope changes
deterministic, the authoritative runtime values are written as LITERALS into
``docker-compose.canary.yml`` and appended to every compose invocation's
``-f`` chain. ``.env`` remains updated as documentation of record.
"""

from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
OVERRIDE_PATH = BASE_DIR / "docker-compose.canary.yml"


def compose_files() -> list[str]:
    files = [
        str(BASE_DIR / "docker-compose.yml"),
        str(BASE_DIR / "docker-compose.dev.yml"),
    ]
    if OVERRIDE_PATH.exists():
        files.append(str(OVERRIDE_PATH))
    return files


def write(mode: str, percent: int, seed: str) -> None:
    if mode not in ("shadow", "disabled"):
        raise ValueError(f"unsupported URL ML mode {mode!r}")
    content = (
        "# Generated by ml/src/canary_override.py - literal canary policy.\n"
        "# This file wins over .env interpolation regardless of shell env.\n"
        "services:\n"
        "  core-api:\n"
        "    environment:\n"
        f"      SAFE_ZONE_URL_ML_MODE: {mode}\n"
        f'      SAFE_ZONE_URL_ML_SHADOW_PERCENT: "{int(percent)}"\n'
        f'      SAFE_ZONE_URL_ML_SHADOW_SEED: "{seed}"\n'
        '      SAFE_ZONE_URL_ML_BASELINE_PATH: "/app/models/safe-zone/url-baseline/operational-baseline.json"\n'
    )
    OVERRIDE_PATH.write_text(content, encoding="utf-8", newline="\n")


def remove() -> None:
    OVERRIDE_PATH.unlink(missing_ok=True)
